# Generated by Django 5.2.7 on 2025-10-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='puntos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
