# Generated by Django 5.2.7 on 2025-10-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cargacombustible_playero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_playero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playero',
            name='is_playero',
            field=models.BooleanField(default=False),
        ),
    ]
